language: ruby
dist: bionic
before_install:
- cp settings.json.example settings.json
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rake
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
rvm:
- 2.7
env:
  global:
    secure: cXDnvMTKGLuEVqZ6GrNQl5VTHrwILS5uJIVJ66UqH8YwmYKPnJdfZQHvScJWbfRK9YfHI/KqfsU/JxCfnOvGms6O6jpOJ7Zgb+6LHjbG5sTMPIg6XFs6zCmviRDDuJVTqQmMqF62Ln8/+RrU83glWLo4HV1OoL8GzKJiKLHaqEWfjGgWCbmfuaixRhNQ55Q8CSJS/jVyJY1eWU7CQq1bC0JHaDkuv65/RPbSRcoBjYijJTsPEj0w49+EoijRGFR45iPbSQm8AP6S1X3LEowgh9G9fA0VUSJBq+2ZZUeCR+O+AVajpvqqryyGzKfAViwHAtptAz1Rq+fOx7eXoFijzX58sZedWEzLeK7hsMdSqHoHxcSsqRxlN6etX0tKqvFzjnfwvxOf8NFwC5eqwgseCJVrzqNHfN5DswnBnfVxryHiZYWUChdzpagqhjtdVMv8bAjp7qg8ImSYEdoHZCAPhNZz6QvV2JZPiLLrI/tJ422FJSxuPauNaHvG/Iq+hf6b52VGy9J8/FNh50ZzH1hI7I2fgQVapZpywg1czFx9k0VUqqL8WzI1y4vPlb40x/gtUU21A4GQNSi+Lv/swYRhsPbZ4QTwNwOOpwNpEs4gwy2wVM8Nj8ytnFryyV+KZTWMe4IoGfLWZeHIO7KwNqJYcldRN6aYjgPgrxn4aFw5UT4=
