version: '2'
volumes:
  elasticsearch:
  redis:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      transport.host: 127.0.0.1
      xpack.security.enabled: "false"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.9
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  newspeek:
    volumes:
      - ".:/app"
    build: .
    command: test
  newspeek-worker:
    depends_on:
      - elasticsearch
      - kibana
      - redis
    image: newspeek
    env_file:
      - .env_file
    command: run_worker
  newspeek-api:
    depends_on:
      - elasticsearch
      - kibana
      - redis
    image: newspeek
    ports:
      - "9292:9292"
    env_file:
      - .env_file
    command: start_server
