# frozen_string_literal: true

source('https://rubygems.org')
gem('activesupport', '6.1.7.1')
gem('addressable', '2.8.0')
gem('airbrake', '~> 5.0')
gem('aws-sdk-s3', '~> 1')
gem('cld')
gem('connection_pool', '2.2.2')
gem('dgaff')
gem('diff-lcs', '1.3')
gem('elasticsearch', '7.10.1')
gem('elasticsearch-api', '7.10.1')
gem('elasticsearch-dsl', '0.1.9')
gem('elasticsearch-persistence', '7.1.1')
gem('fakeredis', '0.8.0')
gem('ffi', '1.12.2')
gem('fuzzy-string-match')
gem('hashie')
gem('i18n', '1.8.2')
gem('json-ld')
gem('mini_portile2', '2.8.0')
gem('matrix')
gem('multi_json', '1.14.1')
gem('nokogiri', '1.13.4')
gem('parallel', '1.19.1')
gem('pry')
gem('public_suffix', '4.0.5')
gem('rack', '2.2.3')
gem('rack-test')
gem('rake')
gem('redis', '4.1.4')
gem('rest-client')
gem('retriable')
gem('rspec')
gem('rubocop')
gem('rubocop-ast', '0.0.3')
gem('rubocop-performance', '1.6.1')
gem('rubocop-rspec', '1.40.0')
gem('ruby-progressbar')
gem('sidekiq')
gem('sidekiq-cron')
gem('sidekiq-unique-jobs')
gem('simplecov', '0.17')
gem('sinatra')
gem('tf-idf-similarity')
gem('webmock')
gem('zeitwerk', '2.3.0')
gem('reline')
