name: Build container

on:
  push:
    branches: ['develop']

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        registry: 848416313321.dkr.ecr.eu-west-1.amazonaws.com
        image_name: newspeek
        image_tag: ${{ github.sha }}