name: Build container

on:
  push:
    branches: ['develop']

jobs:
  Build:
    runs-on: ubuntu-latest

    outputs: 
      image: ${{ steps.build-image.outputs.image }}
    steps:
    - uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Buildx (build)
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fetch
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --output "type=image,push=true" \
          --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --file ./Dockerfile ./
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Setup Code Climate Reporter
      env:
        CC_IMAGE_REPORTER_ID: ${{ secrets.CC_IMAGE_REPORTER_ID }}
        GIT_COMMIT_SHA: ${{ github.sha }}
        GIT_BRANCH: ${{ github.ref }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run Tests
      id: run-test
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fetch
        IMAGE_TAG: ${{ github.sha }}
      run: |
        mkdir coverage
        docker run --rm -v coverage:/app/coverage $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG test
    
    - name: Send data to Code Climate
      run:
        ./cc-test-reporter after-build --exit-code ${{ steps.run-test.outcome }}
  
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Download task definition (qa-fetch)
      run: |
        aws ecs describe-task-definition --task-definition qa-fetch --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition (qa-fetch)
      id: task-def-fetch
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: qa-fetch
        image: ${{ needs.Build.outputs.image }}

    - name: Download task definition (qa-fetch-worker)
      run: |
        aws ecs describe-task-definition --task-definition qa-fetch-worker --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition (qa-fetch-worker)
      id: task-def-worker
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: qa-fetch-worker
        image: ${{ needs.Build.outputs.image }}

    - name: Deploy Amazon ECS task definition (fetch)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-fetch.outputs.task-definition }}
        service: qa-fetch
        cluster: ecs-qa
        wait-for-service-stability: true

    - name: Deploy Amazon ECS task definition (fetch-worker)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-worker.outputs.task-definition }}
        service: qa-fetch-worker
        cluster: ecs-qa
        wait-for-service-stability: true